apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gitlab
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://gitlab.com/gitlab-org/charts/gitlab
    targetRevision:  0.1.0

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: gritlab
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/asongent/gitlab-test.git
#     targetRevision: HEAD
#     path: gitlab
#     helm:
#       valueFiles:
#       - values.yaml
#   destination:
#     namespace: gitlab
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: gitlab-runner
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/asongent/gitlab-test.git
#     targetRevision: HEAD
#     path: gitlab-runner
#   destination:
#     namespace: gitlab
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

# --- 
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: gitlab
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/asongent/gitlab-test.git
#     targetRevision: HEAD
#     path: gitlab
#   destination:
#     namespace: gitlab
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
# --- 
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: ingress
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/asongent/gitlab-test.git
#     targetRevision: HEAD
#     path: ingress
#   destination:
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

# --- 
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: minio
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/asongent/gitlab-test.git
#     targetRevision: HEAD
#     path: minio
#   destination:
#     namespace: gitlab
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true